
Config:
  Ui:
    Image:
      extensions: [jpg,png,gif]
    Process:
      #la idea es usar la extension ypml 
      extensions: [yml]
      Command:       
        start:  
    Editor:
      extensions: [yaml]
    Main:
      Command:
        new:
        open: 
