
Config:
  Ui:
    Image:
      extensions: [jpg,png,gif]
    Process:
      #la idea es usar la extension ypml 
      extensions: [yml]
      Commands:       
      - command: start
        resource: process
      - command: pause
        resource: process
      - command: stop
        resource: process   
    Editor:
      extensions: [yaml]
    Main:
      Commands:
      - command: new
      - command: open 
