Enum:
  ColorConversion:
    BGR2RGB: 4
    BGR2GRAY: 6
    RGB2GRAY: 7
    BGR2HSV: 40 

Type:
  cvImage:
    ctl: CvImage 


Config:
  Task:
    CvtColor:
      description:
      input:
      - name: source 
        type: cvImage
      - name: code 
        type: Enum.ColorConversion
      output:
      - name: default 
        type: cvImage
    ImRead:
      description:
      input:
      - name: filename 
        type: filePath
      output: 
      - name: default
        type: cvImage 
    ImWrite:
      description:
      input:
      - name: filename 
        type: filePath
      - name: img 
        type: cvImage

    



       



 


       
