Enum:
  ColorConversion:
    BGR2RGB: 4
    BGR2GRAY: 6
    RGB2GRAY: 7
    BGR2HSV: 40 

Config:
  Task:
    CvtColor:
      description:
      input:
      - name: source 
        type: image
      - name: code 
        type: Enum.ColorConversion
      output:
      - name: default 
        type: image
    ImRead:
      description:
      input:
      - name: filename 
        type: filePath
      output: 
      - name: default
        type: image 
    ImWrite:
      description:
      input:
      - name: filename 
        type: filePath
      - name: img 
        type: image

    



       



 


       
