Type:
  image:
  int:
  string:
  enum:

Enum:
  ColorConversionCodes:
    values: [COLOR_BGR2GRAY,COLOR_RGB2RGBA]    

Function:
  CvtColor:
    description:
    parameters:
      source: image
      code: enum.ColorConversionCodes
    output: image 


# Process:
#   name: test
#   parameters:
#   activities:
#     - name: start
#       type: Start
#       transitions:
#         - target: a          
#     - name: a
#       type: Task
#       expression: gray = CvtColor($img,COLOR_BGR2GRAY)
       
# Activity:
#   Start:
#   End:
#   Task:


 


       
