
Enum:
  ColorConversionCodes:
    COLOR_BGR2RGB: 4
    COLOR_BGR2GRAY: 6
    COLOR_RGB2GRAY: 7
    COLOR_BGR2HSV: 40   

Task:
  CvtColor:
    description:
    params:
      source: image
      code: enum.ColorConversionCodes
    output: image 



       



 


       
