Process:
  test:
    params:
    nodes:
      star:
        type: Start
        transitions:
          a:           
      a:
        type: Task
        task: CvtColor
        params:
          source: $img
          code: COLOR_BGR2GRAY
        output: gray
        transitions:
          end:  
      end:
        type: End   