Process:
  test:
    params:
    nodes:
      start:
        type: Start
        transitions:
          readImage:
      readImage:
        type: Task
        task: Cv_ImRead
        params:
          filename: /home/flavio/develop/opencv-lab/cvlab/data/test.jpg
        output: img
        transitions:
          transform:                  
      transform:
        type: Task
        task: Cv_CvtColor
        params:
          source: $img
          code: 6
        output: gray
        transitions:
          end:  
      end:
        node: End   