Process:
  test:
    params:
    nodes:
      start:
        type: Start
        transitions:
          readImage:
      readImage:
        type: Task
        task: Cv_ImRead
        params:
          filename: /home/flavio/develop/opencv-lab/cvlab/data/source.jpg
        output: img
        transitions:
          transform:                  
      transform:
        type: Task
        task: Cv_CvtColor
        params:
          source: $img
          code: 6
        output: gray
        transitions:
          save: 
      save:
        type: Task
        task: Cv_ImWrite
        params:
          filename: /home/flavio/develop/opencv-lab/cvlab/data/target.jpg
          img: $gray
        transitions:
          end:         
      end:
        type: End   



        